[package]
name = "Entropy_and_reversible_catalysis"
version = "0.1"
lean_version = "leanprover-community/lean:3.26.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "159e807b89e5ff9e928b7c0729b8dfb6b82cecc6"}
Shannon-theory = {git = "https://github.com/BassemSafieldeen/Shannon-theory.git", rev = "c9f3f869e30d17c6a6db57146a0d8680eb8fab95"}
